### ISSUE TITLE
The checkpoints for ARNIQAs are lost

### ISSUE THREAD

**Issue by YYue000** [chaofengc/IQA-PyTorch#214] opened 2024-11-04 21:54 UTC
Got 404 when using pyiqa.create_metric('arniqa') and wget https://huggingface.co/chaofengc/IQA-PyTorch-Weights/resolve/main/ARNIQA.pth.

Could you upload it again?

**Comment by chaofengc** [comment] 2024-11-05 04:29
Duplicate of #195

**Comment by chaofengc** [comment] 2024-11-05 04:40
Thank you for the information. The weights have been uploaded to huggingface.

**Closed by chaofengc** 2024-11-05 04:40 UTC
